from pathlib import Path

ROOT = Path('fida-field/app/src/main/java/com/fidalix/fidafield')
cloud_path = ROOT / 'CloudSyncFoundation.java'
main_path = ROOT / 'MainActivity.java'
account_path = ROOT / 'AccountTeamManager.java'
gradle_path = Path('fida-field/app/build.gradle')


def replace_once(text: str, old: str, new: str, label: str) -> str:
    if old not in text:
        raise SystemExit(f'0.9.25 patch failed: {label} pattern not found')
    return text.replace(old, new, 1)

# ---- CloudSyncFoundation: authoritative membership preflight + persistent access state ----
s = cloud_path.read_text()
s = replace_once(
    s,
    '    private static final Object SYNC_LOCK=new Object();\n',
    '    private static final Object SYNC_LOCK=new Object();\n'
    '    public static final String KEY_WORKSPACE_ACCESS_STATE="cloud_workspace_access_state";\n'
    '    public static final String KEY_WORKSPACE_ACCESS_ID="cloud_workspace_access_id";\n'
    '    public static final String KEY_WORKSPACE_ACCESS_CHECKED_AT="cloud_workspace_access_checked_at";\n'
    '    public static final String ACCESS_ACTIVE="Active";\n'
    '    public static final String ACCESS_REVOKED="Revoked";\n'
    '    public static final String ACCESS_UNKNOWN="Unknown";\n',
    'cloud access constants'
)

s = replace_once(
    s,
    '    public String backendStatus(){if(!backendConfigured())return "Not configured";return signedIn()?"Connected":"Configured · sign-in required";}\n',
    '    public String backendStatus(){if(!backendConfigured())return "Not configured";return signedIn()?"Connected":"Configured · sign-in required";}\n'
    '    public String workspaceAccessState(){return prefs.getString(KEY_WORKSPACE_ACCESS_STATE,ACCESS_UNKNOWN);}\n'
    '    public String workspaceAccessCheckedAt(){String v=prefs.getString(KEY_WORKSPACE_ACCESS_CHECKED_AT,"");return v.isEmpty()?"Never":v;}\n'
    '    public boolean workspaceAccessRevoked(String workspaceId){String id=prefs.getString(KEY_WORKSPACE_ACCESS_ID,"");return workspaceId!=null&&!workspaceId.isEmpty()&&workspaceId.equals(id)&&ACCESS_REVOKED.equals(prefs.getString(KEY_WORKSPACE_ACCESS_STATE,ACCESS_UNKNOWN));}\n'
    '    private void markWorkspaceAccess(String workspaceId,String state){prefs.edit().putString(KEY_WORKSPACE_ACCESS_ID,workspaceId==null?"":workspaceId).putString(KEY_WORKSPACE_ACCESS_STATE,state==null?ACCESS_UNKNOWN:state).putString(KEY_WORKSPACE_ACCESS_CHECKED_AT,db.now()).apply();}\n',
    'cloud access state helpers'
)

old_first = '''    public WorkspaceMembership firstWorkspace()throws Exception{\n        Object raw=client.rpc("list_my_workspaces",new JSONObject());\n        if(!(raw instanceof JSONArray)||((JSONArray)raw).length()==0)return null;\n        JSONArray a=(JSONArray)raw;String preferred=prefs.getString(AccountTeamManager.KEY_WORKSPACE_ID,"");JSONObject chosen=null;\n        for(int i=0;i<a.length();i++){JSONObject o=a.getJSONObject(i);if(preferred.equals(o.optString("workspace_id"))){chosen=o;break;}}\n        if(chosen==null)chosen=a.getJSONObject(0);\n        return new WorkspaceMembership(chosen.optString("workspace_id"),chosen.optString("workspace_name"),AccountTeamManager.normalizeRole(chosen.optString("role")));\n    }\n'''
new_first = '''    public WorkspaceMembership firstWorkspace()throws Exception{\n        Object raw=client.rpc("list_my_workspaces",new JSONObject());\n        if(!(raw instanceof JSONArray)||((JSONArray)raw).length()==0)return null;\n        JSONArray a=(JSONArray)raw;String preferred=prefs.getString(AccountTeamManager.KEY_WORKSPACE_ID,"");JSONObject chosen=null;\n        for(int i=0;i<a.length();i++){JSONObject o=a.getJSONObject(i);if(preferred.equals(o.optString("workspace_id"))){chosen=o;break;}}\n        if(chosen==null)chosen=a.getJSONObject(0);\n        WorkspaceMembership m=new WorkspaceMembership(chosen.optString("workspace_id"),chosen.optString("workspace_name"),AccountTeamManager.normalizeRole(chosen.optString("role")));markWorkspaceAccess(m.id,ACCESS_ACTIVE);return m;\n    }\n\n    public WorkspaceMembership membershipForWorkspace(String workspaceId)throws Exception{\n        if(workspaceId==null||workspaceId.trim().isEmpty())return null;Object raw=client.rpc("list_my_workspaces",new JSONObject());if(!(raw instanceof JSONArray))return null;JSONArray a=(JSONArray)raw;\n        for(int i=0;i<a.length();i++){JSONObject o=a.getJSONObject(i);if(workspaceId.equals(o.optString("workspace_id"))){WorkspaceMembership m=new WorkspaceMembership(o.optString("workspace_id"),o.optString("workspace_name"),AccountTeamManager.normalizeRole(o.optString("role")));markWorkspaceAccess(workspaceId,ACCESS_ACTIVE);return m;}}return null;\n    }\n\n    public WorkspaceMembership refreshWorkspaceAccess(String workspaceId)throws Exception{\n        if(!backendConfigured())throw new Exception("Supabase backend is not configured");if(!signedIn())throw new Exception("Please sign in first");WorkspaceMembership m=membershipForWorkspace(workspaceId);\n        if(m==null){markWorkspaceAccess(workspaceId,ACCESS_REVOKED);markSyncResult(false,db.now(),"Workspace access disabled or removed");return null;}\n        prefs.edit().putString(AccountTeamManager.KEY_WORKSPACE_NAME,m.name).putString(AccountTeamManager.KEY_ACCOUNT_ROLE,m.role).putBoolean(AccountTeamManager.KEY_CLOUD_WORKSPACE_BOUND,true).apply();return m;\n    }\n'''
s = replace_once(s, old_first, new_first, 'firstWorkspace membership verification')

old_sync_head = '''            if(!backendConfigured())throw new Exception("Supabase backend is not configured");if(!signedIn())throw new Exception("Please sign in first");if(workspaceId==null||workspaceId.isEmpty())throw new Exception("Cloud workspace is not bound");\n            int pushed=0,pulled=0,deferred=0;if(!canManage)db.discardManagerOnlyPendingChanges();String[] pushOrder=canManage?new String[]{"customer","site","asset","technician","job"}:new String[]{"job"};String[] deleteOrder=canManage?new String[]{"job","asset","site","customer","technician"}:new String[]{"job"};List<AppDatabase.Row> pending=db.pendingBusinessSyncRows();java.util.ArrayList<Long> finalizeCompleted=new java.util.ArrayList<>();java.util.HashSet<String> visibleJobIds=new java.util.HashSet<>();\n'''
new_sync_head = '''            if(!backendConfigured())throw new Exception("Supabase backend is not configured");if(!signedIn())throw new Exception("Please sign in first");if(workspaceId==null||workspaceId.isEmpty())throw new Exception("Cloud workspace is not bound");\n            WorkspaceMembership verified=refreshWorkspaceAccess(workspaceId);if(verified==null)throw new Exception("Workspace access is disabled or has been removed. Ask the workspace Owner/Admin to re-enable your account, then check access again.");canManage=AccountTeamManager.ROLE_OWNER.equals(verified.role)||AccountTeamManager.ROLE_ADMIN.equals(verified.role);\n            int pushed=0,pulled=0,deferred=0;if(!canManage)db.discardManagerOnlyPendingChanges();String[] pushOrder=canManage?new String[]{"customer","site","asset","technician","job"}:new String[]{"job"};String[] deleteOrder=canManage?new String[]{"job","asset","site","customer","technician"}:new String[]{"job"};List<AppDatabase.Row> pending=db.pendingBusinessSyncRows();java.util.ArrayList<Long> finalizeCompleted=new java.util.ArrayList<>();java.util.HashSet<String> visibleJobIds=new java.util.HashSet<>();\n'''
s = replace_once(s, old_sync_head, new_sync_head, 'sync membership preflight')
cloud_path.write_text(s)

# ---- AccountTeamManager: binding an active membership clears any prior revoked state ----
s = account_path.read_text()
old_bind = '''        prefs.edit().putString(KEY_WORKSPACE_ID,clean(cloudWorkspaceId)).putString(KEY_WORKSPACE_NAME,clean(name))\n                .putString(KEY_ACCOUNT_ROLE,normalizedRole).putBoolean(KEY_CLOUD_WORKSPACE_BOUND,true).apply();\n'''
new_bind = '''        prefs.edit().putString(KEY_WORKSPACE_ID,clean(cloudWorkspaceId)).putString(KEY_WORKSPACE_NAME,clean(name))\n                .putString(KEY_ACCOUNT_ROLE,normalizedRole).putBoolean(KEY_CLOUD_WORKSPACE_BOUND,true)\n                .putString(CloudSyncFoundation.KEY_WORKSPACE_ACCESS_ID,clean(cloudWorkspaceId)).putString(CloudSyncFoundation.KEY_WORKSPACE_ACCESS_STATE,CloudSyncFoundation.ACCESS_ACTIVE).apply();\n'''
s = replace_once(s, old_bind, new_bind, 'bindCloudWorkspace access state')
account_path.write_text(s)

# ---- MainActivity: lock revoked cloud workspace, live role/access refresh, sync diagnostics ----
s = main_path.read_text()
old_nav_helpers = '''    private void navigate(int id){currentMenu=id;if(id==MENU_DASH)showDashboard();else if(id==MENU_JOBS)showJobs();else if(id==MENU_CUSTOMERS)showCustomers();else if(id==MENU_ASSETS)showAssets();else showMore();}\n    private void setHeader(String a,String b){mainTabScreen=false;title.setText(a);subtitle.setText(b);}\n    private void clear(){content.removeAllViews();}\n    private boolean canSeeAllJobs(){return accountTeam!=null&&accountTeam.canManageTeam();}\n    private boolean canManageWorkspaceSettings(){return accountTeam==null||!accountTeam.hasWorkspace()||accountTeam.canManageTeam();}\n    private boolean canPerformFieldWork(){if(accountTeam==null||!accountTeam.hasWorkspace())return true;String r=accountTeam.accountRole();return AccountTeamManager.ROLE_OWNER.equals(r)||AccountTeamManager.ROLE_ADMIN.equals(r)||AccountTeamManager.ROLE_TECHNICIAN.equals(r);}\n'''
new_nav_helpers = '''    private void navigate(int id){currentMenu=id;if(workspaceAccessRevoked()&&id!=MENU_MORE){showWorkspaceAccessBlocked();return;}if(id==MENU_DASH)showDashboard();else if(id==MENU_JOBS)showJobs();else if(id==MENU_CUSTOMERS)showCustomers();else if(id==MENU_ASSETS)showAssets();else showMore();}\n    private void setHeader(String a,String b){mainTabScreen=false;title.setText(a);subtitle.setText(b);}\n    private void clear(){content.removeAllViews();}\n    private boolean workspaceAccessRevoked(){return cloudSync!=null&&accountTeam!=null&&accountTeam.hasWorkspace()&&cloudSync.workspaceAccessRevoked(accountTeam.workspaceId());}\n    private boolean canSeeAllJobs(){return !workspaceAccessRevoked()&&accountTeam!=null&&accountTeam.canManageTeam();}\n    private boolean canManageWorkspaceSettings(){return !workspaceAccessRevoked()&&(accountTeam==null||!accountTeam.hasWorkspace()||accountTeam.canManageTeam());}\n    private boolean canPerformFieldWork(){if(workspaceAccessRevoked())return false;if(accountTeam==null||!accountTeam.hasWorkspace())return true;String r=accountTeam.accountRole();return AccountTeamManager.ROLE_OWNER.equals(r)||AccountTeamManager.ROLE_ADMIN.equals(r)||AccountTeamManager.ROLE_TECHNICIAN.equals(r);}\n'''
s = replace_once(s, old_nav_helpers, new_nav_helpers, 'navigation access gate')

old_dashboard = '''    private void showDashboard(){\n        currentMenu=MENU_DASH;bottom.getMenu().findItem(MENU_DASH).setChecked(true);setHeader("Fida Field","Service & Maintenance");mainTabScreen=true;clear();LinearLayout b=body(page());\n'''
new_dashboard = '''    private void showWorkspaceAccessBlocked(){\n        currentMenu=MENU_DASH;bottom.getMenu().findItem(MENU_DASH).setChecked(true);setHeader("Workspace access","Access disabled");mainTabScreen=true;clear();LinearLayout b=body(page());\n        b.addView(heroCard("Workspace access disabled","Your local copy is retained, but company workspace data and field actions are locked until your access is re-enabled and verified."));\n        b.addView(info("Workspace",accountTeam.workspaceName()));b.addView(info("Account",cloudSync.accountEmail().isEmpty()?accountTeam.accountEmail():cloudSync.accountEmail()));b.addView(info("Last access check",cloudSync.workspaceAccessCheckedAt()));\n        MaterialButton check=button("Check access again");check.setEnabled(cloudSync.backendConfigured()&&cloudSync.signedIn());check.setOnClickListener(v->runCloud("Checking workspace access…",()->cloudSync.refreshWorkspaceAccess(accountTeam.workspaceId()),obj->{CloudSyncFoundation.WorkspaceMembership wm=(CloudSyncFoundation.WorkspaceMembership)obj;if(wm==null){toast("Workspace access is still disabled");showWorkspaceAccessBlocked();}else{accountTeam.bindCloudWorkspace(wm.id,wm.name,wm.role);toast("Workspace access restored · "+wm.role);showDashboard();}}));b.addView(check);\n        MaterialButton account=outlineButton("Account & workspace");account.setOnClickListener(v->showAccountWorkspace());b.addView(account);MaterialButton sync=outlineButton("Cloud sync status");sync.setOnClickListener(v->showCloudSync());b.addView(sync);\n        b.addView(paragraph("An Owner or Admin can re-enable this member from People & Team. Existing jobs and history are not deleted when access is disabled."));\n    }\n\n    private void showDashboard(){\n        if(workspaceAccessRevoked()){showWorkspaceAccessBlocked();return;}\n        currentMenu=MENU_DASH;bottom.getMenu().findItem(MENU_DASH).setChecked(true);setHeader("Fida Field","Service & Maintenance");mainTabScreen=true;clear();LinearLayout b=body(page());\n'''
s = replace_once(s, old_dashboard, new_dashboard, 'workspace blocked screen')

old_refresh = '''        MaterialButton refresh=outlineButton("Refresh workspace membership");refresh.setOnClickListener(v->runCloud("Checking memberships…",()->cloudSync.firstWorkspace(),obj->{CloudSyncFoundation.WorkspaceMembership wm=(CloudSyncFoundation.WorkspaceMembership)obj;if(wm==null)toast("No cloud workspace membership found");else{accountTeam.bindCloudWorkspace(wm.id,wm.name,wm.role);toast("Workspace refreshed");}showAccountWorkspace();}));b.addView(refresh);\n'''
new_refresh = '''        MaterialButton refresh=outlineButton("Refresh workspace membership");refresh.setOnClickListener(v->runCloud("Checking memberships…",()->accountTeam.hasCloudWorkspace()?cloudSync.refreshWorkspaceAccess(accountTeam.workspaceId()):cloudSync.firstWorkspace(),obj->{CloudSyncFoundation.WorkspaceMembership wm=(CloudSyncFoundation.WorkspaceMembership)obj;if(wm==null){toast(accountTeam.hasCloudWorkspace()?"Workspace access is disabled or removed":"No cloud workspace membership found");}else{accountTeam.bindCloudWorkspace(wm.id,wm.name,wm.role);toast("Workspace refreshed · "+wm.role);}if(workspaceAccessRevoked())showWorkspaceAccessBlocked();else showAccountWorkspace();}));b.addView(refresh);\n'''
s = replace_once(s, old_refresh, new_refresh, 'account membership refresh')

old_cloud_info = '''        b.addView(section("Workspace"));b.addView(info("Workspace",accountTeam.hasWorkspace()?accountTeam.workspaceName():"Not set up"));b.addView(info("Role",accountTeam.accountRole().isEmpty()?"Local user":accountTeam.accountRole()));b.addView(info("Cloud binding",accountTeam.hasCloudWorkspace()?"Bound":"Local only"));\n        b.addView(section("Supabase"));b.addView(info("Status",cloudSync.backendStatus()));b.addView(info("Account",cloudSync.accountEmail().isEmpty()?"Not signed in":cloudSync.accountEmail()));b.addView(info("Last sync",cloudSync.lastSync()));b.addView(info("Last result",cloudSync.lastResult()));\n'''
new_cloud_info = '''        b.addView(section("Workspace"));b.addView(info("Workspace",accountTeam.hasWorkspace()?accountTeam.workspaceName():"Not set up"));b.addView(info("Role",accountTeam.accountRole().isEmpty()?"Local user":accountTeam.accountRole()));b.addView(info("Cloud binding",accountTeam.hasCloudWorkspace()?"Bound":"Local only"));b.addView(info("Workspace access",workspaceAccessRevoked()?"Disabled":cloudSync.workspaceAccessState()));b.addView(info("Access checked",cloudSync.workspaceAccessCheckedAt()));\n        b.addView(section("Supabase"));b.addView(info("Status",cloudSync.backendStatus()));b.addView(info("Account",cloudSync.accountEmail().isEmpty()?"Not signed in":cloudSync.accountEmail()));b.addView(info("Last sync",cloudSync.lastSync()));b.addView(info("Last result",cloudSync.lastResult()));\n'''
s = replace_once(s, old_cloud_info, new_cloud_info, 'cloud access diagnostics')

old_sync_button = '''        MaterialButton sync=button("Sync now");sync.setEnabled(cloudSync.backendConfigured()&&cloudSync.signedIn()&&accountTeam.hasCloudWorkspace());sync.setOnClickListener(v->runCloud("Synchronizing workspace…",()->cloudSync.syncNow(accountTeam.workspaceId(),accountTeam.canManageTeam()),obj->{CloudSyncFoundation.SyncResult r=(CloudSyncFoundation.SyncResult)obj;refreshEntitlementsAndBranding();toast(r.message);recreate();}));b.addView(sync);\n'''
new_sync_button = '''        if(cloudSync.signedIn()&&accountTeam.hasCloudWorkspace()){MaterialButton accessCheck=outlineButton("Check workspace access");accessCheck.setOnClickListener(v->runCloud("Checking workspace access…",()->cloudSync.refreshWorkspaceAccess(accountTeam.workspaceId()),obj->{CloudSyncFoundation.WorkspaceMembership wm=(CloudSyncFoundation.WorkspaceMembership)obj;if(wm==null){toast("Workspace access is disabled");showWorkspaceAccessBlocked();}else{accountTeam.bindCloudWorkspace(wm.id,wm.name,wm.role);toast("Access active · "+wm.role);showCloudSync();}}));b.addView(accessCheck);}\n        MaterialButton sync=button("Sync now");sync.setEnabled(cloudSync.backendConfigured()&&cloudSync.signedIn()&&accountTeam.hasCloudWorkspace()&&!workspaceAccessRevoked());sync.setOnClickListener(v->runCloud("Synchronizing workspace…",()->cloudSync.syncNow(accountTeam.workspaceId(),accountTeam.canManageTeam()),obj->{CloudSyncFoundation.SyncResult r=(CloudSyncFoundation.SyncResult)obj;refreshEntitlementsAndBranding();toast(r.message);recreate();}));b.addView(sync);\n'''
s = replace_once(s, old_sync_button, new_sync_button, 'sync access check button')

s = s.replace('Fida Field 0.9.24 Test', 'Fida Field 0.9.25 Test')
s = s.replace('Report-number collision protection and professional field-service workflows by Fidalix.', 'Workspace access enforcement, live role verification and resilient multi-device synchronization by Fidalix.')
main_path.write_text(s)

# ---- Version ----
s = gradle_path.read_text()
s = replace_once(s, '        versionCode 27\n        versionName \'0.9.24-test\'\n', '        versionCode 28\n        versionName \'0.9.25-test\'\n', 'version bump')
gradle_path.write_text(s)

print('Applied Fida Field 0.9.25 access + sync hardening patch')
