package com.fidalix.fidafield;

import android.content.Context;
import android.content.SharedPreferences;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.RectF;
import android.graphics.pdf.PdfDocument;
import android.net.Uri;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

public class PdfReport {
    private static final int W = 595, H = 842, M = 42;
    private static final int TEXT = Color.rgb(45,49,45), MUTED = Color.rgb(103,108,102);

    private static class Writer {
        final PdfDocument doc = new PdfDocument();
        PdfDocument.Page page;
        Canvas c;
        int pageNo = 0;
        float y;
        final Paint p = new Paint(Paint.ANTI_ALIAS_FLAG);
        final String company;
        final String reportNo;
        final int primary, accent, highlight;
        final Bitmap logo;

        Writer(String company, String reportNo, int primary, int accent, int highlight, Bitmap logo) { this.company=company; this.reportNo=reportNo;this.primary=primary;this.accent=accent;this.highlight=highlight;this.logo=logo;newPage(); }
        void newPage() {
            if (page != null) { footer(); doc.finishPage(page); }
            pageNo++;
            PdfDocument.PageInfo info=new PdfDocument.PageInfo.Builder(W,H,pageNo).create();
            page=doc.startPage(info);c=page.getCanvas();y=M;
            p.setStyle(Paint.Style.FILL);p.setColor(accent);c.drawRect(0,0,W,6,p);p.setColor(highlight);c.drawRect(W*0.72f,0,W,6,p);
            if(logo!=null){float maxW=118,maxH=30;float sc=Math.min(maxW/logo.getWidth(),maxH/logo.getHeight());float dw=logo.getWidth()*sc,dh=logo.getHeight()*sc;c.drawBitmap(logo,null,new RectF(M,13,M+dw,13+dh),p);}else{p.setTextSize(9);p.setColor(MUTED);c.drawText(company,M,27,p);}
            p.setTextSize(9);p.setColor(MUTED);p.setTextAlign(Paint.Align.RIGHT);c.drawText(reportNo,W-M,27,p);p.setTextAlign(Paint.Align.LEFT);
            y=52;
        }
        void ensure(float need){if(y+need>H-52)newPage();}
        void footer(){p.setTextSize(8);p.setColor(MUTED);c.drawLine(M,H-35,W-M,H-35,p);c.drawText("Generated by Fida Field",M,H-20,p);p.setTextAlign(Paint.Align.RIGHT);c.drawText("Page "+pageNo,W-M,H-20,p);p.setTextAlign(Paint.Align.LEFT);}
        void finish(){footer();doc.finishPage(page);page=null;}
        void title(String s){ensure(40);p.setColor(TEXT);p.setTextSize(24);p.setFakeBoldText(true);c.drawText(s,M,y+24,p);p.setFakeBoldText(false);y+=38;}
        void labelValue(String label,String value){if(value==null||value.trim().isEmpty())return;ensure(34);p.setTextSize(8);p.setColor(MUTED);p.setFakeBoldText(true);c.drawText(label.toUpperCase(Locale.US),M,y+9,p);p.setFakeBoldText(false);y+=14;text(value,11,TEXT,14);y+=4;}
        void section(String s){ensure(30);y+=5;p.setColor(primary);p.setTextSize(13);p.setFakeBoldText(true);c.drawText(s,M,y+13,p);p.setFakeBoldText(false);y+=20;p.setColor(Color.rgb(215,223,221));c.drawRect(M,y,W-M,y+1,p);y+=10;}
        void text(String text,float size,int color,float line){if(text==null||text.isEmpty())return;p.setTextSize(size);p.setColor(color);p.setFakeBoldText(false);List<String> lines=wrap(text,p,W-2*M);for(String ln:lines){ensure(line+2);c.drawText(ln,M,y+line-3,p);y+=line;}}
        void badge(String label){ensure(24);p.setTextSize(9);float tw=p.measureText(label)+18;p.setColor(blend(accent,Color.WHITE,0.88f));c.drawRoundRect(new RectF(M,y,M+tw,y+20),10,10,p);p.setColor(accent);p.setFakeBoldText(true);c.drawText(label,M+9,y+14,p);p.setFakeBoldText(false);y+=28;}
        void photo(Bitmap b,String caption){if(b==null)return;float maxW=W-2*M,maxH=280;float sc=Math.min(maxW/b.getWidth(),maxH/b.getHeight());float dw=b.getWidth()*sc,dh=b.getHeight()*sc;ensure(dh+30);float left=M+(maxW-dw)/2;p.setStyle(Paint.Style.FILL);c.drawBitmap(b,null,new RectF(left,y,left+dw,y+dh),p);y+=dh+5;if(caption!=null&&!caption.isEmpty()){p.setTextSize(8);p.setColor(MUTED);c.drawText(caption,M,y+9,p);y+=15;}y+=8;}
        static int blend(int a,int b,float amount){amount=Math.max(0f,Math.min(1f,amount));return Color.rgb(Math.round(Color.red(a)*(1-amount)+Color.red(b)*amount),Math.round(Color.green(a)*(1-amount)+Color.green(b)*amount),Math.round(Color.blue(a)*(1-amount)+Color.blue(b)*amount));}
        static List<String> wrap(String text,Paint p,float max){ArrayList<String> out=new ArrayList<>();for(String para:text.replace("\r","").split("\n",-1)){if(para.isEmpty()){out.add("");continue;}String[] words=para.split(" ");StringBuilder line=new StringBuilder();for(String w:words){String test=line.length()==0?w:line+" "+w;if(p.measureText(test)<=max)line=new StringBuilder(test);else{if(line.length()>0)out.add(line.toString());line=new StringBuilder(w);}}if(line.length()>0)out.add(line.toString());}return out;}
    }

    public static File generate(Context context, AppDatabase db, long jobId, SharedPreferences prefs) throws Exception {
        AppDatabase.Row j=db.getJob(jobId); if(j.id()==0)throw new IllegalArgumentException("Job not found");
        String company=prefs.getString("company_name","Fidalix Limited");
        String companyPhone=prefs.getString("company_phone","");
        String companyEmail=prefs.getString("company_email","");
        String companyAddress=prefs.getString("company_address","Kigali, Rwanda");
        EntitlementManager entitlements=new EntitlementManager(prefs,db);BrandingManager branding=new BrandingManager(prefs,entitlements.isPro());Bitmap brandLogo=branding.loadCustomLogo(context);
        Writer w=new Writer(company,j.s("report_no"),branding.primary(),branding.accent(),branding.highlight(),brandLogo);
        w.title("Service Report");
        w.badge(j.s("status") + "  •  " + j.s("priority") + " priority");
        w.labelValue("Report number",j.s("report_no"));
        w.labelValue("Service date",j.s("job_date"));
        w.labelValue("Technician",j.s("technician"));
        w.section("Customer & Site");
        w.labelValue("Customer",j.s("customer_name"));
        w.labelValue("Site",j.s("site_name"));
        w.labelValue("Asset",(j.s("asset_tag").isEmpty()?"":j.s("asset_tag")+" — ")+j.s("asset_name"));
        w.section("Service Summary");
        w.labelValue("Job",j.s("title"));
        w.labelValue("Reported problem",j.s("problem"));
        w.labelValue("Diagnosis",j.s("diagnosis"));
        w.labelValue("Work performed",j.s("work_done"));
        w.labelValue("Parts / materials",j.s("parts"));
        w.labelValue("Next recommended service",j.s("next_service"));

        List<AppDatabase.Row> photos=db.photos(jobId);
        if(!photos.isEmpty()){
            w.section("Photos"); int idx=1;
            for(AppDatabase.Row ph:photos){Bitmap b=null;InputStream in=null;try{in=context.getContentResolver().openInputStream(Uri.parse(ph.s("uri")));if(in!=null)b=BitmapFactory.decodeStream(in);}catch(Exception ignored){}finally{try{if(in!=null)in.close();}catch(Exception ignored){}}if(b!=null){w.photo(b,"Photo "+idx+(ph.s("caption").isEmpty()?"":" — "+ph.s("caption")));b.recycle();}idx++;}
        }
        if(!j.s("signature_path").isEmpty()){
            Bitmap sig=null;try(InputStream in=new FileInputStream(j.s("signature_path"))){sig=BitmapFactory.decodeStream(in);}catch(Exception ignored){}
            if(sig!=null){w.section("Customer Acceptance");w.labelValue("Signed by",j.s("customer_name_signed"));w.photo(sig,"Customer signature");sig.recycle();}
        }
        w.section("Service Provider");
        w.labelValue("Company",company);
        w.labelValue("Address",companyAddress);
        w.labelValue("Phone",companyPhone);
        w.labelValue("Email",companyEmail);
        w.text("This report records the service activity performed on the date shown above. Any follow-up recommendations should be scheduled separately unless otherwise stated.",9,MUTED,12);
        w.finish();
        File dir=new File(context.getFilesDir(),"reports");if(!dir.exists()&&!dir.mkdirs())throw new Exception("Unable to create reports directory");
        File file=new File(dir,j.s("report_no").replaceAll("[^A-Za-z0-9._-]","_")+".pdf");
        try(FileOutputStream out=new FileOutputStream(file)){w.doc.writeTo(out);}finally{w.doc.close();if(brandLogo!=null&&!brandLogo.isRecycled())brandLogo.recycle();}
        return file;
    }
}
