package com.fidalix.fidafield;

import android.content.Context;
import android.content.SharedPreferences;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.RectF;
import android.graphics.pdf.PdfDocument;
import android.net.Uri;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

/** Professional A4 service-report renderer for Fida Field. */
public class ProfessionalPdfReport {
    private static final int W=595,H=842,M=38;
    private static final int TEXT=Color.rgb(39,43,39),MUTED=Color.rgb(105,111,104),LINE=Color.rgb(224,228,223),PANEL=Color.rgb(247,248,246);

    private static class Writer {
        final PdfDocument doc=new PdfDocument();
        final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);
        final int primary,accent,highlight;
        final String company,reportNo;
        final Bitmap logo;
        PdfDocument.Page page; Canvas c; float y; int pageNo;

        Writer(String company,String reportNo,int primary,int accent,int highlight,Bitmap logo){
            this.company=company;this.reportNo=reportNo;this.primary=primary;this.accent=accent;this.highlight=highlight;this.logo=logo;newPage();
        }

        void newPage(){
            if(page!=null){footer();doc.finishPage(page);}
            pageNo++;
            page=doc.startPage(new PdfDocument.PageInfo.Builder(W,H,pageNo).create());c=page.getCanvas();
            p.setStyle(Paint.Style.FILL);p.setColor(primary);c.drawRect(0,0,W,8,p);p.setColor(accent);c.drawRect(W*0.66f,0,W,8,p);p.setColor(highlight);c.drawRect(W*0.88f,0,W,8,p);
            if(logo!=null){float maxW=128,maxH=34;float sc=Math.min(maxW/logo.getWidth(),maxH/logo.getHeight());float dw=logo.getWidth()*sc,dh=logo.getHeight()*sc;c.drawBitmap(logo,null,new RectF(M,20,M+dw,20+dh),p);}else{
                p.setColor(primary);p.setTextSize(17);p.setFakeBoldText(true);c.drawText(company,M,43,p);p.setFakeBoldText(false);
            }
            p.setTextAlign(Paint.Align.RIGHT);p.setTextSize(9);p.setColor(MUTED);p.setFakeBoldText(true);c.drawText("SERVICE REPORT",W-M,28,p);p.setFakeBoldText(false);p.setTextSize(11);p.setColor(TEXT);c.drawText(reportNo,W-M,45,p);p.setTextAlign(Paint.Align.LEFT);
            p.setColor(LINE);c.drawRect(M,61,W-M,62,p);y=78;
        }

        void ensure(float need){if(y+need>H-58)newPage();}
        void footer(){
            p.setColor(LINE);c.drawRect(M,H-40,W-M,H-39,p);p.setTextSize(8);p.setColor(MUTED);p.setTextAlign(Paint.Align.LEFT);c.drawText(company+"  •  Generated by Fida Field",M,H-22,p);p.setTextAlign(Paint.Align.RIGHT);c.drawText("Page "+pageNo,W-M,H-22,p);p.setTextAlign(Paint.Align.LEFT);
        }
        void finish(){footer();doc.finishPage(page);page=null;}

        void reportHero(String title,String status,String date,String customer){
            ensure(104);RectF box=new RectF(M,y,W-M,y+92);p.setColor(PANEL);c.drawRoundRect(box,16,16,p);p.setColor(primary);c.drawRoundRect(new RectF(M,y,M+6,y+92),6,6,p);
            p.setColor(MUTED);p.setTextSize(9);p.setFakeBoldText(true);c.drawText("SERVICE ACTIVITY",M+18,y+20,p);p.setFakeBoldText(false);
            p.setColor(TEXT);p.setTextSize(22);p.setFakeBoldText(true);drawEllipsized(title,M+18,y+48,W-M-155);p.setFakeBoldText(false);
            p.setTextSize(10);p.setColor(MUTED);String meta=(customer==null?"":customer)+(date==null||date.isEmpty()?"":"  •  "+date);drawEllipsized(meta,M+18,y+70,W-M-155);
            badge(status,W-M-126,y+24,108);
            y+=108;
        }

        void badge(String text,float x,float top,float width){
            if(text==null||text.trim().isEmpty())text="Status";int fg=primary,bg=blend(primary,Color.WHITE,.90f);String l=text.toLowerCase(Locale.US);if(l.contains("complete")){fg=Color.rgb(36,118,78);bg=Color.rgb(233,247,239);}else if(l.contains("cancel")||l.contains("urgent")){fg=Color.rgb(170,62,55);bg=Color.rgb(255,239,238);}else if(l.contains("progress")){fg=accent;bg=blend(accent,Color.WHITE,.88f);}p.setColor(bg);c.drawRoundRect(new RectF(x,top,x+width,top+30),15,15,p);p.setColor(fg);p.setTextSize(9);p.setFakeBoldText(true);p.setTextAlign(Paint.Align.CENTER);c.drawText(text,x+width/2,top+19,p);p.setTextAlign(Paint.Align.LEFT);p.setFakeBoldText(false);
        }

        void section(String title){
            ensure(34);y+=3;p.setColor(blend(primary,Color.WHITE,.94f));c.drawRoundRect(new RectF(M,y,W-M,y+27),8,8,p);p.setColor(primary);c.drawRect(M,y,M+4,y+27,p);p.setTextSize(11);p.setFakeBoldText(true);c.drawText(title.toUpperCase(Locale.US),M+13,y+18,p);p.setFakeBoldText(false);y+=38;
        }

        void two(String l1,String v1,String l2,String v2){
            boolean a=has(v1),b=has(v2);if(!a&&!b)return;float gap=12,col=(W-2*M-gap)/2f;float h=Math.max(fieldHeight(v1,col-24),fieldHeight(v2,col-24));ensure(h+8);if(a)fieldBox(l1,v1,M,y,col,h);if(b)fieldBox(l2,v2,M+col+gap,y,col,h);y+=h+10;
        }

        void field(String label,String value){if(!has(value))return;float h=fieldHeight(value,W-2*M-28);ensure(h+8);fieldBox(label,value,M,y,W-2*M,h);y+=h+10;}

        float fieldHeight(String value,float max){if(!has(value))return 0;p.setTextSize(10.5f);int lines=wrap(value,p,max).size();return Math.max(48,30+lines*14);}
        void fieldBox(String label,String value,float left,float top,float width,float height){
            p.setStyle(Paint.Style.FILL);p.setColor(Color.WHITE);c.drawRoundRect(new RectF(left,top,left+width,top+height),10,10,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(1);p.setColor(LINE);c.drawRoundRect(new RectF(left,top,left+width,top+height),10,10,p);p.setStyle(Paint.Style.FILL);
            p.setTextSize(8);p.setColor(MUTED);p.setFakeBoldText(true);c.drawText(label.toUpperCase(Locale.US),left+12,top+17,p);p.setFakeBoldText(false);p.setTextSize(10.5f);p.setColor(TEXT);float yy=top+34;for(String line:wrap(value,p,width-24)){c.drawText(line,left+12,yy,p);yy+=14;}
        }

        void photo(Bitmap b,String caption){
            if(b==null)return;float maxW=W-2*M-8,maxH=300;float sc=Math.min(maxW/b.getWidth(),maxH/b.getHeight());float dw=b.getWidth()*sc,dh=b.getHeight()*sc;ensure(dh+52);float left=M+(W-2*M-dw)/2f;RectF frame=new RectF(left-4,y,left+dw+4,y+dh+8);p.setColor(Color.WHITE);c.drawRoundRect(frame,10,10,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(1);p.setColor(LINE);c.drawRoundRect(frame,10,10,p);p.setStyle(Paint.Style.FILL);c.drawBitmap(b,null,new RectF(left,y+4,left+dw,y+4+dh),p);y+=dh+15;if(has(caption)){p.setTextSize(8.5f);p.setColor(MUTED);c.drawText(caption,M,y+8,p);y+=16;}y+=8;
        }

        void signature(Bitmap sig,String signedBy){
            ensure(145);RectF box=new RectF(M,y,W-M,y+126);p.setColor(Color.WHITE);c.drawRoundRect(box,12,12,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(1);p.setColor(LINE);c.drawRoundRect(box,12,12,p);p.setStyle(Paint.Style.FILL);p.setTextSize(8);p.setColor(MUTED);p.setFakeBoldText(true);c.drawText("CUSTOMER ACCEPTANCE",M+14,y+20,p);p.setFakeBoldText(false);if(sig!=null){float maxW=210,maxH=62;float sc=Math.min(maxW/sig.getWidth(),maxH/sig.getHeight());float dw=sig.getWidth()*sc,dh=sig.getHeight()*sc;c.drawBitmap(sig,null,new RectF(M+14,y+32,M+14+dw,y+32+dh),p);}p.setColor(LINE);c.drawRect(M+14,y+99,W-M-14,y+100,p);p.setTextSize(9);p.setColor(TEXT);c.drawText(has(signedBy)?signedBy:"Customer representative",M+14,y+116,p);p.setTextAlign(Paint.Align.RIGHT);p.setColor(MUTED);c.drawText("Signature on file",W-M-14,y+116,p);p.setTextAlign(Paint.Align.LEFT);y+=140;
        }

        void note(String value){if(!has(value))return;List<String> lines; p.setTextSize(9);lines=wrap(value,p,W-2*M-28);float h=24+lines.size()*12;ensure(h);p.setColor(blend(accent,Color.WHITE,.93f));c.drawRoundRect(new RectF(M,y,W-M,y+h),10,10,p);p.setColor(MUTED);float yy=y+18;for(String line:lines){c.drawText(line,M+14,yy,p);yy+=12;}y+=h+10;}

        void drawEllipsized(String text,float x,float baseline,float max){if(text==null)text="";String out=text;if(p.measureText(out)>max){while(out.length()>1&&p.measureText(out+"…")>max)out=out.substring(0,out.length()-1);out+="…";}c.drawText(out,x,baseline,p);}
        static boolean has(String s){return s!=null&&!s.trim().isEmpty();}
        static int blend(int a,int b,float amount){amount=Math.max(0,Math.min(1,amount));return Color.rgb(Math.round(Color.red(a)*(1-amount)+Color.red(b)*amount),Math.round(Color.green(a)*(1-amount)+Color.green(b)*amount),Math.round(Color.blue(a)*(1-amount)+Color.blue(b)*amount));}
        static List<String> wrap(String text,Paint p,float max){ArrayList<String> out=new ArrayList<>();if(text==null)return out;for(String para:text.replace("\r","").split("\n",-1)){if(para.isEmpty()){out.add("");continue;}String[] words=para.split(" ");StringBuilder line=new StringBuilder();for(String word:words){String test=line.length()==0?word:line+" "+word;if(p.measureText(test)<=max){line=new StringBuilder(test);}else{if(line.length()>0)out.add(line.toString());if(p.measureText(word)<=max)line=new StringBuilder(word);else{StringBuilder piece=new StringBuilder();for(char ch:word.toCharArray()){String t=piece.toString()+ch;if(p.measureText(t)>max&&piece.length()>0){out.add(piece.toString());piece=new StringBuilder();}piece.append(ch);}line=piece;}}}if(line.length()>0)out.add(line.toString());}return out;}
    }

    private static String serviceTime(long millis){if(millis<=0)return "";return new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm",Locale.US).format(new java.util.Date(millis));}
    private static String serviceDuration(AppDatabase db,AppDatabase.Row j){if(j.l("service_started_at_ms")<=0)return "";long minutes=db.jobServiceDurationMinutes(j.id());String value;if(minutes<1)value="< 1 min";else{long h=minutes/60,m=minutes%60;value=h>0?h+" h"+(m>0?" "+m+" min":""):m+" min";}if(j.l("service_completed_at_ms")>0)return value;return (db.jobServiceRunning(j.id())?"Running · ":"Paused · ")+value;}

    public static File generate(Context context,AppDatabase db,long jobId,SharedPreferences prefs)throws Exception{
        AppDatabase.Row j=db.getJob(jobId);if(j.id()==0)throw new IllegalArgumentException("Job not found");
        String company=prefs.getString("company_name","Fidalix Limited");String companyPhone=prefs.getString("company_phone","");String companyEmail=prefs.getString("company_email","");String companyAddress=prefs.getString("company_address","Kigali, Rwanda");
        EntitlementManager entitlements=new EntitlementManager(prefs,db);BrandingManager branding=new BrandingManager(prefs,entitlements.isPro());Bitmap logo=branding.loadCustomLogo(context);Writer w=new Writer(company,j.s("report_no"),branding.primary(),branding.accent(),branding.highlight(),logo);

        w.reportHero(j.s("title"),j.s("status"),j.s("job_date"),j.s("customer_name"));
        w.section("Report details");w.two("Report number",j.s("report_no"),"Priority",j.s("priority"));w.two("Service date",j.s("job_date"),"Technician",j.s("technician"));w.two("First service start",serviceTime(j.l("service_started_at_ms")),"Service finished",serviceTime(j.l("service_completed_at_ms")));w.field("Active service duration",serviceDuration(db,j));w.field("Work sessions",db.jobServiceSessionSummary(jobId));
        w.section("Customer & site");w.two("Customer",j.s("customer_name"),"Contact",j.s("customer_contact"));w.two("Email",j.s("customer_email"),"Phone",j.s("customer_phone"));w.field("Customer address",j.s("customer_address"));w.two("Site",j.s("site_name"),"Site contact",j.s("site_contact"));w.field("Site address",j.s("site_address"));w.field("Asset",(j.s("asset_tag").isEmpty()?"":j.s("asset_tag")+" — ")+j.s("asset_name"));
        w.section("Service summary");w.field("Reported problem",j.s("problem"));w.field("Diagnosis",j.s("diagnosis"));w.field("Work performed",j.s("work_done"));w.field("Parts / materials",j.s("parts"));w.two("Next recommended service",j.s("next_service"),"Status",j.s("status"));

        List<AppDatabase.Row> photos=db.photos(jobId);if(!photos.isEmpty()){w.section("Photographic evidence");int idx=1;for(AppDatabase.Row ph:photos){Bitmap b=null;InputStream in=null;try{in=context.getContentResolver().openInputStream(Uri.parse(ph.s("uri")));if(in!=null)b=BitmapFactory.decodeStream(in);}catch(Exception ignored){}finally{try{if(in!=null)in.close();}catch(Exception ignored){}}if(b!=null){w.photo(b,"Photo "+idx+(ph.s("caption").isEmpty()?"":" — "+ph.s("caption")));b.recycle();}idx++;}}

        if(!j.s("signature_path").isEmpty()){Bitmap sig=null;try(InputStream in=new FileInputStream(j.s("signature_path"))){sig=BitmapFactory.decodeStream(in);}catch(Exception ignored){}if(sig!=null){w.section("Customer acceptance");w.signature(sig,j.s("customer_name_signed"));sig.recycle();}}

        w.section("Service provider");w.two("Company",company,"Phone",companyPhone);w.two("Email",companyEmail,"Address",companyAddress);w.note("This document records the service activity completed on the date shown. Follow-up recommendations, replacement work or future maintenance should be scheduled separately unless explicitly included in this report.");
        w.finish();

        File dir=new File(context.getFilesDir(),"reports");if(!dir.exists()&&!dir.mkdirs())throw new Exception("Unable to create reports directory");File file=new File(dir,j.s("report_no").replaceAll("[^A-Za-z0-9._-]","_")+".pdf");try(FileOutputStream out=new FileOutputStream(file)){w.doc.writeTo(out);}finally{w.doc.close();if(logo!=null&&!logo.isRecycled())logo.recycle();}return file;
    }
}
